[package]
name = "intervals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comparable_bound = { git = "https://github.com/Wooker/comparable_bound" }